---
version: '3'


networks:
  db_network:
    driver: bridge
  app_network:
    driver: bridge


services:

  database:
    build: services/database
    hostname: "database"
    networks:
      - db_network

  backend:
    build: backend
    image: backend_image
    # volumes:
    #   - ./backend:/code
    hostname: "backend_app"
    depends_on:
      - database
    networks:
      - db_network
      - app_network

  nginx:
    build: services/nginx
    ports:
      # - "80:80"
      # - "443:443"
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - backend
      - rabbitmq
      - web
      - celery

  rabbitmq:
    build: services/rabbitmq
    hostname: "rabbitmq"
    networks:
      - app_network

  celery:
    build: services/celery
    # volumes:
    #   - ./backend:/code
    #   - ./services/celery/config:/code/config/celery/
    hostname: "celery"
    working_dir: /code
    networks:
      - db_network
      - app_network
    depends_on:
      - backend
      - rabbitmq

  web:
    build:
      context: web
      dockerfile: Dockerfile-prod
    image: web_image
    volumes:
      - ./web:/usr/src/app
    hostname: "web"
    networks:
      - app_network
#    environment:
#      - NODE_ENV: 'production'

...
