FROM rabbitmq:3.6-management-alpine 


# RUN rm -rf /var/lib/rabbitmq/mnesia
# RUN rabbitmq-plugins enable rabbitmq_management

# Add custom settings here
# modify default user credentials etc.
